version: '3.7'

services:
  # Databases
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - -c
      - "listen_addresses=*"
      - -p
      - "${POSTGRES_POST}"
  db_setup:
    image: selene-backend
    restart: "on-failure"
    depends_on:
      - db
    links:
      - db
    volumes:
      - shared:/shared
    command:
      - /opt/wait-for-postgres.sh
      - db
      - bash
      - -c
      - "cd /opt/selene/selene-backend/db/scripts && pipenv run python -u bootstrap_mycroft_db.py && touch /shared/db_bootstrap_done"
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_HOST: "db"
  redis:
    image: redis:5.0.7
    restart: always

  # Applications
  sso:
    image: selene-backend
    restart: "on-failure"
    volumes:
      - shared:/shared
    links:
      - db
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "while [ ! -f /shared/db_bootstrap_done ]; do echo 'Database bootstraping not done. Exiting.'; sleep 5; done;
        cd /opt/selene/selene-backend/api/sso && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini"
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${POSTGRES_POST}"
      DB_USER: selene
      GITHUB_CLIENT_ID: <github client id> TODO
      GITHUB_CLIENT_SECRET: <github client secret> TODO
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      JWT_RESET_SECRET: "${JWT_RESET_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      SENDGRID_API_KEY: <sendgrid API key> TODO
      SSO_BASE_URL: "${SSO_BASE_URL}"
  account:
    image: selene-backend
    restart: "on-failure"
    volumes:
      - shared:/shared
    links:
      - db
      - redis
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/account && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH_BASE_URL: "${OAUTH_BASE_URL}"
  skills_setup:
    image: selene-backend
    restart: "on-failure"
    volumes:
      - shared:/shared
    links:
      - db
      - redis
    command:
      - bash
      - -c
      - "if [ ! -f /shared/db_bootstrap_done ]; then echo 'Database bootstraping not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/batch && /usr/local/bin/pipenv install &&  pipenv run python script/load_skill_display_data.py --core-version 19.08 && touch /shared/skills_setup_done
        "
        # TODO: core-version shouldn't be hardcoded (get latest somehow?)
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      GITHUB_USER: "${GITHUB_USER}"
      GITHUB_PASSWORD: "${GITHUB_PASSWORD}"
  market:
    image: selene-backend
    restart: "on-failure"
    volumes:
      - shared:/shared
    links:
      - db
      - redis
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/skills_setup_done ]; then echo 'Skills downloading and setup not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/market && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini
        "
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH_BASE_URL: "${OAUTH_BASE_URL}"
  devices:
    image: selene-backend
    restart: "on-failure"
    volumes:
      - shared:/shared
    links:
      - db
      - redis
    expose:
      - "4000"
    command:
      - bash
      - -c
      - "if [ ! -f /shared/skills_setup_done ]; then echo 'Skills downloading and setup not done. Exiting.'; exit 1; fi;
         cd /opt/selene/selene-backend/api/public && /usr/local/bin/pipenv run uwsgi -b 32768 --http 0.0.0.0:4000 --ini uwsgi.ini"
    environment:
      DB_HOST: db
      DB_NAME: mycroft
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_USER: selene
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
      SALT: "${ENCRYPTION_SALT}"
      SELENE_ENVIRONMENT: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OAUTH_BASE_URL: "${OAUTH_BASE_URL}"
      EMAIL_SERVICE_HOST: "${EMAIL_SERVICE_HOST}"
      EMAIL_SERVICE_PORT: "${EMAIL_SERVICE_PORT}"
      EMAIL_SERVICE_USER: "${EMAIL_SERVICE_USER}"
      EMAIL_SERVICE_PASSWORD: "${EMAIL_SERVICE_PASSWORD}"
      GOOGLE_STT_KEY: "${GOOGLE_STT_KEY}" # NOTE: Optional if you plan to use Google for STT
      OWM_KEY: "${OWM_KEY}"
      OWM_URL: "https://api.openweathermap.org/data/2.5"
      WOLFRAM_ALPHA_KEY: "${WOLFRAM_ALPHA_KEY}"
      WOLFRAM_ALPHA_URL: "https://api.wolframalpha.com"

  # UI
  selene-ui-market:
    image: selene-ui-market
    restart: "on-failure"
  selene-ui-account:
    image: selene-ui-account
    restart: "on-failure"
  selene-ui-sso:
    image: selene-ui-sso
    restart: "on-failure"
  # This is and nginx reverse proxy that redirects all subdomains and api
  # endpoints to the correct container.
  selene-ui-proxy:
    image: mycroft-nginx-proxy
    restart: "on-failure"
    links:
      - market
      - sso
      - account
      - devices
      - selene-ui-market
      - selene-ui-sso
    depends_on:
      - market
      - sso
      - account
      - devices
      - selene-ui-market
      - selene-ui-sso
    ports:
      - "80:80"
      - "443:443"

volumes:
  generated:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/generated"
      o: bind
  shared:
